<?php
define ('DEBUG', 0);
define ('ALWAYS_PASS_CAPTCHA', 0);
define ('_MODULES_CONFIGURATION_BASE_PATH', dirname(__FILE__));
define ('_MODULES_CONFIGURATION_SITE_PATH', _MODULES_CONFIGURATION_BASE_PATH);
define ('_MODULES_CONFIGURATION_INCLUDE_PATH', dirname(__FILE__) . '/include');
define ('_MODULES_CONFIGURATION_TEMPLATE_CACHE_CONTROL', '?template=av-159&colorScheme=blue&header=headers3&button=buttons3');
define ('_MODULES_CONFIGURATION_SITE_API_PATH', _MODULES_CONFIGURATION_SITE_PATH.'/data/settings/api.php');
define ('_MODULES_CONFIGURATION_SITE_PASSWORD_PATH', _MODULES_CONFIGURATION_SITE_PATH.'/data/settings/pwd.php');
define ('_MODULES_CONFIGURATION_SITE_LANG', 'es_ES');
define ('_MODULES_CONFIGURATION_STORAGE_ATTACH_PATH', 'data/storage/attachments');
define ('_MODULES_CONFIGURATION_STORAGE_TYPE', 'publish');
define ('_MODULES_CONFIGURATION_TMP_PATH', _MODULES_CONFIGURATION_BASE_PATH.'/data/tmp');
define ('_MODULES_CONFIGURATION_TMP_URL', 'data/tmp/');
define ('_MODULES_CONFIGURATION_SETTINGS_PATH', _MODULES_CONFIGURATION_SITE_PATH.'/data/settings');
define ('_MODULES_CONFIGURATION_SETTINGS_ATTACHMENTS_BASE_URL', '');
define ('_MODULES_CONFIGURATION_LOGIN_MODULE_ID', '5zwbvo7o26i');
$_configurationModulesInstance = array (
	'tawaufjsxf0' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'rm87hmoz3j0' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'linyiw7vkcq' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'hayaqp6opxh' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'spkidrru1l9' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'7khrxtyns22' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'rf5k2pei8ui' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'5zwbvo7o26i' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Registro',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'fam00bt1zfb' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'zgjavrwzd1p' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'eihe2reakc2' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'w00y4dy0eh5' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'wbztjsikh0d' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'7zmy29t0fmg' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'ycwcf0mazbu' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'a86wqc0f2a7' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'eb0llax6oa0' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'zo1udz9ppeu' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'0aab8gpnkfv' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'5e44klhwvx7' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'swo6z7gh2k1' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Comentarios',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'l7eijf05fn6' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'i7k0n9aulcs' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Comentarios',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'd13empwy6sk' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'47yddnw6xqy' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'pldr6cn0pyb' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'2x6pprxckkg' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'5otovajq9pl' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'dps2i1dyhoq' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
	'i51gnsb19la' => array (
		'TRANSPORT' => 'direct',
		'STORAGE_ATTACHMENTS_BASE_URL' => '',
		'STORAGE_BASE_PATH' => _MODULES_CONFIGURATION_BASE_PATH,
		'STORAGE_DB_DSN' => 'sqlite:///'._MODULES_CONFIGURATION_BASE_PATH.'/data/storage/sb_modules.php',
		'MODULE_NAME' => 'Script',
		'VERSION' => '4.5.0',
		'REQUIRED_API_VERSION' => '4.5.0',
	),
);
define ('LOCALE_DECIMAL_POINT', ',');
define ('LOCALE_MONETARY_UNIT_CODE', 'EUR');
define ('LOCALE_CURRENCY_SYMBOL_LEFT', '€');
define ('LOCALE_CURRENCY_SYMBOL_RIGHT', '');
define ('LOCALE_DATE_FORMAT', 'd/m/Y');
define ('LOCALE_TIME_FORMAT', 'G:i:s');
define ('LOCALE_WEEK_BEGIN', '1');
?>